name: Cleanup packages

on:
  schedule:
  - cron: '21 10 * * *'
  workflow_dispatch:

jobs:
  clean-pr-packages:

    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - uses: actions/delete-package-versions@v4
      with:
        package-name: CenterEdge.TruffleApi
        package-type: nuget
        min-versions-to-keep: 30
        ignore-versions: ^(?!.*ci-pr).*$
